
package org.fr.rsi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImageServerImplService", targetNamespace = "http://rsi.fr.org/", wsdlLocation = "http://x-wing123:8080/WebServiceGlass-1.0-SNAPSHOT/ImageServerImplService?wsdl")
public class ImageServerImplService
    extends Service
{

    private final static URL IMAGESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGESERVERIMPLSERVICE_EXCEPTION;
    private final static QName IMAGESERVERIMPLSERVICE_QNAME = new QName("http://rsi.fr.org/", "ImageServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://x-wing123:8080/WebServiceGlass-1.0-SNAPSHOT/ImageServerImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGESERVERIMPLSERVICE_WSDL_LOCATION = url;
        IMAGESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public ImageServerImplService() {
        super(__getWsdlLocation(), IMAGESERVERIMPLSERVICE_QNAME);
    }

    public ImageServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGESERVERIMPLSERVICE_QNAME, features);
    }

    public ImageServerImplService(URL wsdlLocation) {
        super(wsdlLocation, IMAGESERVERIMPLSERVICE_QNAME);
    }

    public ImageServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGESERVERIMPLSERVICE_QNAME, features);
    }

    public ImageServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImageServerImpl
     */
    @WebEndpoint(name = "ImageServerImplPort")
    public ImageServerImpl getImageServerImplPort() {
        return super.getPort(new QName("http://rsi.fr.org/", "ImageServerImplPort"), ImageServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageServerImpl
     */
    @WebEndpoint(name = "ImageServerImplPort")
    public ImageServerImpl getImageServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rsi.fr.org/", "ImageServerImplPort"), ImageServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw IMAGESERVERIMPLSERVICE_EXCEPTION;
        }
        return IMAGESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
